name: Archive Locally and Send to IA
on:
  #schedule:
  #  - cron: '0 */12 * * *'  # Run every 12 hours
  workflow_dispatch:  # Allow manual triggering

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Select URLs
      run: |
        shuf -n 100 output_urls.txt > selected_urls.txt
    - name: Upload selected URLs
      uses: actions/upload-artifact@v2
      with:
        name: selected-urls
        path: selected_urls.txt

  archive-and-submit:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4 internetarchive
    - name: Download selected URLs
      uses: actions/download-artifact@v2
      with:
        name: selected-urls
    - name: Configure Internet Archive credentials
      env:
        IA_ACCESS_KEY: ${{ secrets.IA_ACCESS_KEY }}
        IA_SECRET_KEY: ${{ secrets.IA_SECRET_KEY }}
      run: |
        echo "[s3]
        access = $IA_ACCESS_KEY
        secret = $IA_SECRET_KEY" > ~/.ia
    - name: Run archiving script
      run: python archive_local_send_to_ia.py

  update-output-file:
    needs: archive-and-submit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download selected URLs
      uses: actions/download-artifact@v2
      with:
        name: selected-urls
    - name: Remove archived URLs from output file
      run: |
        grep -vFf selected_urls.txt output_urls.txt > temp_urls.txt
        mv temp_urls.txt output_urls.txt
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add output_urls.txt
        git diff --quiet && git diff --staged --quiet || git commit -m "Remove archived URLs from output_urls.txt"
        git push

  cleanup:
    needs: update-output-file
    runs-on: ubuntu-latest
    steps:
    - name: Remove artifacts
      uses: geekyeggo/delete-artifact@v1
      with:
        name: selected-urls
