name: Parallel Process Output URLs
on:
  schedule:
    - cron: '0 */12 * * *'  # Run every 12 hours
  workflow_dispatch:  # Allow manual triggering

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Select and split URLs
      run: |
        shuf -n 100 output_urls.txt > selected_urls.txt
        split -n l/5 -d selected_urls.txt url_part_
    - name: Upload URL parts
      uses: actions/upload-artifact@v2
      with:
        name: url-parts
        path: url_part_*

  archive-urls:
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      matrix:
        part: [0, 1, 2, 3, 4]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install ArchiveBox
      run: |
        pip install archivebox
    - name: Download URL part
      uses: actions/download-artifact@v2
      with:
        name: url-parts
    - name: Initialize and configure ArchiveBox
      run: |
        mkdir archivebox_data
        cd archivebox_data
        archivebox init > /dev/null 2>&1
        archivebox config --set SAVE_ARCHIVE_DOT_ORG=True
        archivebox config --set SAVE_TITLE=False
        archivebox config --set SAVE_FAVICON=False
        archivebox config --set SAVE_WGET=False
        archivebox config --set SAVE_WARC=False
        archivebox config --set SAVE_PDF=False
        archivebox config --set SAVE_SCREENSHOT=False
        archivebox config --set SAVE_DOM=False
        archivebox config --set SAVE_SINGLEFILE=False
        archivebox config --set SAVE_READABILITY=False
        archivebox config --set SAVE_MERCURY=False
        archivebox config --set SAVE_GIT=False
        archivebox config --set SAVE_MEDIA=False
        archivebox config --set USE_COLOR=False
        archivebox config --set SHOW_PROGRESS=False
    - name: Archive URLs
      run: |
        cd archivebox_data
        while read url; do
          echo "Archiving: $url"
          archivebox add "$url" > /dev/null 2>&1
        done < ../url_part_0${{ matrix.part }}
    - name: Clean up
      run: |
        rm -rf archivebox_data

  cleanup:
    needs: archive-urls
    runs-on: ubuntu-latest
    steps:
    - name: Remove artifacts
      uses: geekyeggo/delete-artifact@v1
      with:
        name: url-parts
